sonar.projectKey=nexus-project
sonar.projectName=Nexus
sonar.sources=nexus,nexus_backend
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/.venv/**,nexus_backend/tests/**
sonar.tests=nexus_backend/tests
sonar.python.version=3
sonar.python.coverage.reportPaths=nexus_backend/coverage.xml
sonar.sourceEncoding=UTF-8
